const jelzo = [
    "Nagy",
    "Otromba",
    "Kapzsi",
    "Büdös",
    "Alamuszi",
    "Idétlen",
    "Vézna",
    "Szellemes",
    "Kattant",
    "Zsivány",
    "Haldokló",
    "Dagadt",
    "Embertelen",
    "Megtépázott",
    "Suttyó",
    "Nagyszájú",
    "Kellemetlen",
    "Förtelmes",
]

const nev = [
    "Orgre",
    "Tanár",
    "Kismatyka",
    "Gizsgugya",
    "Kacsacsőrű emlős",
    "Varázsló",
    "Jehova tanúja",
    "Sárkánygriff",
    "Fegyverhordozó",
    "Ork",
    "Hobgoblin",
    "Nyálka",
    "Farkas",
    "Zombimalacember",
    "Sírásó",
    "Anyós",
]